FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel

WORKDIR /app

COPY requirements-gpu.txt ./

RUN apt update && \
  apt install -y --no-install-recommends ffmpeg \
  wget

RUN python3 -m pip install -r requirements-gpu.txt