FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel

WORKDIR /app

COPY requirements.txt ./

RUN apt update && \
  apt install -y --no-install-recommends ffmpeg \
  wget \
  python3-dev \
  python3-pip \
  python3-setuptools \
  python3-wheel && \
  python3 -m pip install -r requirements-gpu.txt