FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04

WORKDIR /app

COPY requirements.txt ./

RUN apt update && \
  apt install -y --no-install-recommends ffmpeg wget python3-dev

RUN python -m pip install -r requirements.txt